export enum ApplicationModulesEnum {
  BONNA_HUB_ALL_USERS = "BONNA HUB - USUARIOS",
  BONNA_HUB_MANAGE_PERMISSIONS = "BONNA HUB - PERMISOS",
  BONNA_HUB_APPLICATIONS_AND_MODULES = "BONNA HUB - APLICACIONES Y MÓDULOS",
  BONNA_HUB_MANAGE_PASSWORD_POLICY = "BONNA HUB - POLÍTICA DE CONTRASEÑAS",
}
