interface CaseReportOriginal {
  id: string;
  ori_cr_dateofcase: string;
  ori_cr_casetype_id_fk: number;
  ori_cr_filingnumber: string;
  ori_cr_documentpatient: string | null;
  ori_cr_doctypepatient: string | null;
  ori_cr_firstnamepatient: string | null;
  ori_cr_secondnamepatient: string | null;
  ori_cr_firstlastnamepatient: string | null;
  ori_cr_secondlastnamepatient: string | null;
  ori_cr_agepatient: string | null;
  ori_cr_genderpatient: string | null;
  ori_cr_epspatient: string | null;
  ori_cr_admconsecutivepatient: number | null;
  ori_cr_diagnosticcodepatient: string | null;
  ori_cr_diagnosticdescriptionpatient: string | null;
  ori_cr_foliopatient: string | null;
  ori_cr_anonymoususer: boolean;
  ori_cr_fullnamereporter: string | null;
  ori_cr_documentreporter: string | null;
  ori_cr_eventtype_id_fk: number;
  ori_cr_originservice_id_fk: number;
  ori_cr_reportingservice_id_fk: number;
  ori_cr_event_id_fk: number;
  ori_cr_descriptionothers: string | null;
  ori_cr_risktype_id_fk: number | null;
  ori_cr_severityclasif_id_fk: number | null;
  ori_cr_origin_id_fk: number;
  ori_cr_suborigin_id_fk: number;
  ori_cr_risklevel_id_fk: number | null;
  ori_cr_priority_id_fk: number | null;
  ori_cr_statusmovement_id_fk: number;
  ori_cr_characterization_id_fk: number | null;
  ori_cr_infoprovidedfamily: boolean;
  ori_cr_clinicalfollowrequired: boolean;
  ori_cr_observationscharacterization: string | null;
  ori_cr_description: string;
  ori_cr_inmediateaction: string | null;
  ori_cr_materializedrisk: boolean | null;
  ori_cr_associatedpatient: boolean;
  ori_cr_status: boolean;
  createdAt: string;
  updateAt: string;
  deletedAt: string | null;
  medicine?: MedicineCaseReport[];
  device?: DeviceCaseReport[];
}
