interface CaseReportValidate {
  id: string;
  val_cr_dateofcase: string;
  val_cr_consecutive_id: number;
  val_cr_previous_id: number;
  val_cr_originalcase_id_fk: string;
  val_cr_casetype_id_fk: number;
  val_cr_filingnumber: string;
  val_cr_documentpatient: string | null;
  val_cr_doctypepatient: string | null;
  val_cr_firstnamepatient: string | null;
  val_cr_secondnamepatient: string | null;
  val_cr_firstlastnamepatient: string | null;
  val_cr_secondlastnamepatient: string | null;
  val_cr_agepatient: string | null;
  val_cr_genderpatient: string | null;
  val_cr_epspatient: string | null;
  val_cr_admconsecutivepatient: number | null;
  val_cr_diagnosticcodepatient: string | null;
  val_cr_diagnosticdescriptionpatient: string | null;
  val_cr_foliopatient: string | null;
  val_cr_anonymoususer: boolean;
  val_cr_fullnamereporter: string | null;
  val_cr_documentreporter: string | null;
  val_cr_eventtype_id_fk: number;
  val_cr_originservice_id_fk: number;
  val_cr_reportingservice_id_fk: number;
  val_cr_event_id_fk: number;
  val_cr_descriptionothers: string | null;
  isVisibleDesriptionOther: boolean;
  val_cr_risktype_id_fk: number | null;
  val_cr_severityclasif_id_fk: number | null;
  val_cr_origin_id_fk: number;
  val_cr_suborigin_id_fk: number;
  val_cr_risklevel_id_fk: number | null;
  val_cr_priority_id_fk: number | null;
  val_cr_statusmovement_id_fk: number;
  val_cr_characterization_id_fk: number | null;
  val_cr_infoprovidedfamily: boolean;
  val_cr_clinicalfollowrequired: boolean;
  val_cr_observationscharacterization: string | null;
  val_cr_description: string;
  val_cr_inmediateaction: string | null;
  val_cr_materializedrisk: boolean | null;
  val_cr_associatedpatient: boolean;
  val_cr_validated: boolean;
  val_cr_status: boolean;
  createdAt: string;
  updateAt: string;
  deletedAt: string | null;
  medicines?: MedicineCaseReport[];
  devices?: DeviceCaseReport[];
  caseType?: CaseType;
  event?: Events;
  reportingService?: Service;
  eventType?: EventType;
  reportAnalystAssignment?: ReportAnalystAssignment;
  reportResearcherAssignment?: ReportResearcherAssignment;
  movementReport?: MovementReport;
  synergy?: Synergy;
  characterizationCase?: CharacterizationCase;
  priority?: Priority;
  severityClasification?: SeverityClasification;
  // caseReportOriginal?: CaseReportOriginal;
  // unit: Unit;
  // riskType: [];
  // origin: [];
  // subOrigin: [];
  // riskLevel: [];
  // originService: [];
}
