interface CaseReportValidate {
  id: string;
  val_cr_consecutive_id: number;
  val_cr_previous_id: number;
  val_cr_originalcase_id_fk: string;
  val_cr_casetype_id_fk: number;
  val_cr_filingnumber: string;
  val_cr_documentpatient: string | null;
  val_cr_doctypepatient: string | null;
  val_cr_firstnamepatient: string | null;
  val_cr_secondnamepatient: string | null;
  val_cr_firstlastnamepatient: string | null;
  val_cr_secondlastnamepatient: string | null;
  val_cr_agepatient: number | null;
  val_cr_genderpatient: string | null;
  val_cr_epspatient: string | null;
  val_cr_admconsecutivepatient: number | null;
  val_cr_reporter_id: number;
  val_cr_eventtype_id_fk: number;
  val_cr_originservice_id_fk: number;
  val_cr_reportingservice_id_fk: number;
  val_cr_event_id_fk: number;
  val_cr_risktype_id_fk: number | null;
  val_cr_severityclasif_id_fk: number | null;
  val_cr_origin_id_fk: number;
  val_cr_suborigin_id_fk: number;
  val_cr_risklevel_id_fk: number | null;
  val_cr_priority_id_fk: number | null;
  val_cr_statusmovement_id_fk: number;
  val_cr_characterization_id_fk: number | null;
  val_cr_infoprovidedfamily: boolean | null;
  val_cr_clinicalfollowrequired: boolean | null;
  val_cr_observationscharacterization: string | null;
  val_cr_description: string | null;
  val_cr_inmediateaction: string | null;
  val_cr_materializedrisk: boolean | null;
  val_cr_associatedpatient: boolean | null;
  val_cr_validated: boolean;
  val_cr_status: boolean;
  createdAt: string;
  updateAt: string;
  deletedAt: string | null;
  // movementReport: MovementReport;
  // caseType: CaseType;
  // severityClasification: SeverityClasification;
  // event: Event;
  // unit: Unit;
  // priority: Priority;
  // riskType: [];
  // origin: [];
  // subOrigin: [];
  // riskLevel: [];
  // eventType: [];
  // originService: [];
  // reportingService: [];
  // reportAnalystAssignment: [];
  // reportResearcherAssignment: [];
  // synergy: [];
  // characterizationCase: [];
  // caseReportOriginal: [];
}
