export enum CaseTypeReportEnum {
  RISK = 'RIESGO',
  ADVERSE_EVENT = 'EVENTO ADVERSO',
  INCIDENT = 'INCIDENTE',
  INDICATING_UNSAFE_CARE = 'INDICIO DE ATENCIÓN INSEGURA',
  COMPLICATIONS = 'COMPLICACIONES',
}
