export enum logReports {
  LOG_CREATION = 'REGISTRÓ EL CASO',
  LOG_VALIDATION = 'VALIDÓ EL CASO',
  LOG_ANULATION = 'ANULÓ EL CASO',
  LOG_ASSIGNMENT_ANALYST = 'ASIGNÓ A ANALISTA',
  LOG_REASSIGNMENT_ANALYST = 'REASIGNÓ A ANALISTA',
  LOG_RETURN_CASE_ANALYST = 'DEVOLVIÓ A ANALISTA',
  LOG_RETURN_CASE_VALIDATOR = 'DEVOLVIÓ A VALIDADOR',
  LOG_ASSIGNMENT_RESEARCHER = 'ASIGNÓ A INVESTIGADOR',
  LOG_REASSIGNMENT_RESEARCHER = 'REASIGNÓ A INVESTIGADOR',
  LOG_CASE_RAISED_SYNERGY_COMMITTEE = 'ELEVÓ CASO A COMITÉ DE SINERGIA',
  LOG_CASE_RESCHEDULED_SYNERGY = 'REPROGRAMÓ CASO EN SINERGIA',
  LOG_SOLUTION_CASE_SYNERGY = 'SOLUCIONÓ CASO EN SINERGIA',
}
