export enum UserRolesEnum {
  VALIDATOR = 'VALIDADOR',
  ANALYST = 'ANALISTA',
  INVESTIGATOR = 'INVESTIGADOR',
  PATIENT = 'PACIENTE',
  REPORTER = 'REPORTANTE',
  RISK_CONTROLLER = 'CONTROLADOR DE RIESGO',
  AUDITOR = 'AUDITOR',
  SP_PROGRAM = 'PROGRAMA SP',
  PARAMETERIZER = 'PARAMETRIZADOR',
}
