export enum ItemNames {
  ITEM_DASHBOARD = "Dashboard",
  ITEM_NOTIFICATIONS = "Notificaciones",
  ITEM_CREATE_REPORT = "Crear Reporte",
  ITEM_SUMMARY = "Resumen",
  ITEM_SYNERGY = "Sinergia",

  ITEM_VALIDATION = "Validación",
  SUB_VALIDATE_CASES = "Validar Casos",
  SUB_OTHER_CASES = "Otros Casos",

  ITEM_ANALYSIS = "Análisis",
  SUB_CASE_ASSIGNMENT = "Asignación de casos",
  SUB_MY_CASE = "Mis casos",
  SUB_INFORMATION = "Informes",

  ITEM_FOLLOW_UPS = "Seguimientos",

  ITEM_ACTION_PLANS = "Planes de acción",
  SUB_PLANS_CREATED = "Planes Creados",
  SUB_MONITORING = "Monitoreo",

  ITEM_RISK = "Riesgo",
  SUB_RISK_ANALYSIS = "Análisis de riesgo",
  SUB_RISK_SUMMARY = "Resumen",
  SUB_RISK_MATRIX = "Matriz de riesgo",
  SUB_RISK_INFORMATION = "Informe",

  ITEM_SP_PROGRAM = "Programa de SP",
  SUB_STRATEGIES = "Estrategias",
  SUB_SP_INFORMATION = "Informe",
  SUB_SANCTIONS_FRAMEWORK = "Marco de sanciones",

  ITEM_CLOSING_CYCLE = "Cierre de ciclo",
  ITEM_INDICATORS = "Indicadores",

  ITEM_CONFIGURATION = "Configuración",
  SUB_EVENT_TYPE = "Tipos de Suceso",
  SUB_EVENT = "Sucesos",
  SUB_CASE_TYPES = "Tipos de caso",
  SUB_RISK_TYPES = "Tipos de riesgo",
  SUB_SEVERITY_CLASIFICATIONS = "Clasificaciones de severidad",
  SUB_PRIORITIES = "Prioridades",
  SUB_UNITS = "Unidades",
  SUB_SERVICES = "Servicios",
  SUB_ORIGINS = "Origenes",
  SUB_SUB_ORIGINS = "Sub Origenes",
  SUB_RISK_LEVELS = "Niveles de riesgo",
  SUB_CASE_CHARACTERIZATION = "Caracterización de caso",
  SUB_ROLE = "Roles",
  SUB_RESEARCH_INSTRUMENTS = "Instrumentos de investigación",
  SUB_DEVICE_TYPES = "Tipos de dispositivo",
  SUB_DAMAGE_TYPES = "Tipos de daño",
  SUB_FLUID_TYPES = "Tipos de fluido",
  SUB_INFLUENCY_FACTORS = "Factores de influencia",
  SUB_FAILED_MEASURES = "Medidas fallidas",
  SUB_RISK_FACTORS = "Factores de riesgo",
  SUB_SAFETY_BARRIERS = "Barreras de seguridad",
  SUB_PROTOCOLS = "Protocolos",
  SUB_UNSAFE_ACTIONS = "Acciones inseguras",
  SUB_RETURN_REASONS_CASE = "Razones de devolución de casos",
  SUB_MOVEMENTS = "Movimientos",
  SUB_ONCOLOGICAL_CATEGORY = "Categoría oncológica",
}

export enum ItemKeys {
  ITEM_DASHBOARD_KEY = "dashboard",
  ITEM_NOTIFICATIONS_KEY = "notifications",
  ITEM_CREATE_REPORT_KEY = "create_report",
  ITEM_SUMMARY_KEY = "summary_report",
  ITEM_SYNERGY_KEY = "synergy",

  ITEM_VALIDATION_KEY = "validation",
  SUB_VALIDATE_CASES_KEY = "validate_report",
  SUB_OTHER_CASES_KEY = "validate_others_report",

  ITEM_ANALYSIS_KEY = "cases_analysis",
  SUB_CASE_ASSIGNMENT_KEY = "case_assignment",
  SUB_MY_CASE_KEY = "my_cases",
  SUB_CASE_INFORMATION_KEY = "cases_information",

  ITEM_FOLLOW_UPS_KEY = "follow_ups",

  ITEM_ACTION_PLANS_KEY = "action_plans",
  SUB_PLANS_CREATED_KEY = "plans_created",
  SUB_MONITORING_KEY = "monitoring",

  ITEM_RISK_KEY = "risk",
  SUB_RISK_ANALYSIS_KEY = "risk_analysis",
  SUB_RISK_SUMMARY_KEY = "risk_summary",
  SUB_RISK_MATRIX_KEY = "risk_matrix",
  SUB_RISK_INFORMATION_KEY = "risk_information",

  ITEM_SP_PROGRAM_KEY = "sp_program",
  SUB_STRATEGIES_KEY = "sp_strategies",
  SUB_SP_INFORMATION_KEY = "sp_information",
  SUB_SANCTIONS_FRAMEWORK_KEY = "sanctions_framework",

  ITEM_CLOSING_CYCLE_KEY = "closing_cycle",
  ITEM_INDICATORS_KEY = "indicators",

  ITEM_CONFIGURATION_KEY = "configuration",
  SUB_EVENT_TYPE_KEY = "configuration/event_type",
  SUB_EVENT_KEY = "configuration/event",
  SUB_CASE_TYPES_KEY = "configuration/case_type",
  SUB_RISK_TYPES_KEY = "configuration/risk_type",
  SUB_SEVERITY_CLASIFICATIONS_KEY = "configuration/severity_clasification",
  SUB_PRIORITIES_KEY = "configuration/priority",
  SUB_UNITS_KEY = "configuration/unit",
  SUB_SERVICES_KEY = "configuration/service",
  SUB_ORIGINS_KEY = "configuration/origin",
  SUB_SUB_ORIGINS_KEY = "configuration/sub_origin",
  SUB_RISK_LEVELS_KEY = "configuration/risk_level",
  SUB_CASE_CHARACTERIZATION_KEY = "configuration/characterization_case",
  SUB_ROLE_KEY = "configuration/role",
  SUB_RESEARCH_INSTRUMENTS_KEY = "configuration/research_instrument",
  SUB_DEVICE_TYPES_KEY = "configuration/device_type",
  SUB_DAMAGE_TYPES_KEY = "configuration/damage_type",
  SUB_FLUID_TYPES_KEY = "configuration/fluid_type",
  SUB_INFLUENCY_FACTORS_KEY = "configuration/influencing_factor",
  SUB_FAILED_MEASURES_KEY = "configuration/failed_measure",
  SUB_RISK_FACTORS_KEY = "configuration/risk_factor",
  SUB_SAFETY_BARRIERS_KEY = "configuration/safety_barrier",
  SUB_PROTOCOLS_KEY = "configuration/protocol",
  SUB_UNSAFE_ACTIONS_KEY = "configuration/unsafe_action",
  SUB_RETURN_REASONS_CASE_KEY = "configuration/reason_return_case",
  SUB_MOVEMENTS_KEY = "configuration/movement_report",
  SUB_ONCOLOGICAL_CATEGORY_KEY = "configuration/oncology_category",
}
